---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}

library(tidyverse)
library(p8105.datasets)

library(viridis)
library(flexdashboard)
library(plotly)
```




```{r}
data("ny_noaa")
ny_noaa = ny_noaa |>
  filter(!is.na(tmax), !is.na(tmin), !is.na(prcp)) |> # remove NA
  sample_n(1000) # Random pick 1000 data to reduce the size of dataset
```

Column {data-width=650}
-----------------------------------------------------------------------

### Scatterplot

```{r}
ny_noaa |>
  mutate(text_label = paste("Max Temp: ", tmax, "10°C", "\nMin Temp: ", tmin, "10°C")) |>
  plot_ly(
    x = ~tmin,
    y = ~tmax,
    type = "scatter",
    mode = "markers",
    marker = list(
      size = 5,
      opacity = 0.6,
      color = ~tmax,      
      colorscale = "Viridis", 
      colorbar = list(title = "Max Temp (10°C)")
    ),
    text = ~text_label  
  ) |>
  layout(
    title = "Max Temperature vs Min Temperature",
    xaxis = list(title = "Min Temperature (10°C)"),
    yaxis = list(title = "Max Temperature (10°Ç)")
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Barchart

```{r}
ny_noaa |>
  filter(!is.na(prcp)) |>
  mutate(prcp_group = cut(prcp, breaks = seq(0, max(prcp, na.rm = TRUE), by = 10), right = FALSE)) |>
  count(prcp_group) |>
  filter(!is.na(prcp_group)) |>  # remove NA group
  mutate(color = viridis(n())) |>
  plot_ly(x = ~prcp_group, y = ~n, type = "bar", marker = list(color = ~color))|>
  layout(
    title = "prcp distribution",
    xaxis = list(title = "prcp group (1/10 mm)"),
    yaxis = list(title = "Frequency")
  )
```

### Boxplot

```{r}
ny_noaa = ny_noaa |>
  mutate(
    tmax = as.numeric(tmax),
    month = month(date, label = TRUE)
  )

plot_ly(
  data = ny_noaa,
  x = ~month,
  y = ~tmax,
  type = "box",
  marker = list(
    color = ~as.numeric(month),  
    colorscale = "Viridis"       
  )
) |>
  layout(
    title = "Max Temperature Distribution in Each Month",
    xaxis = list(title = "Month"),
    yaxis = list(title = "Highest Temperature (10°C)")
  )
```

